language: python
python: "2.7"
install: bash ./setup.sh
script: source env/bin/activate && python ./littlebro/manage.py test littlebro
notifications:
  webhooks:
    urls:
      - http://hooks.littlebro.io/travisci
    on_success: always
    on_failure: never
    on_start: false